# Generated by Django 6.0.4 on 2026-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_date',
            field=models.DateField(),
        ),
    ]
