# Generated by Django 6.0.4 on 2026-04-08 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('name', models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
        ),
    ]
