# Generated by Django 6.0.4 on 2026-04-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default='https://cdn.britannica.com/92/152292-050-EAF28A45/Bald-eagle.jpg'),
        ),
    ]
