# Generated by Django 6.0.4 on 2026-04-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('task', '0002_alter_task_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='taks',
            field=models.ManyToManyField(to='task.task'),
        ),
    ]
