# Generated by Django 6.0.4 on 2026-04-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_taks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='taks',
            new_name='task',
        ),
    ]
