# Generated by Django 6.0.4 on 2026-04-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_taks_category_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='task',
        ),
    ]
