# Generated by Django 6.0.3 on 2026-04-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_remove_student_id_student_fathers_name_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
    ]
